### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by Njasa2k** [LituRout/RB-Modulation#1]
I noticed the note in the issues section stating that the code will be released soon. Could you please provide an update on the expected timeline for the release? Access to the code would be greatly appreciated.

**Comment by zhanghongyong123456** [comment]
> I noticed the note in the issues section stating that the code will be released soon. Could you please provide an update on the expected timeline for the release? Access to the code would be greatly appreciated.

+1

**Comment by Adenialzz** [comment]
+1

**Comment by s9anus98a** [comment]
what for is code release? how about model release?

**Comment by loboere** [comment]
please authors answer this question

**Comment by poluramus** [comment]
Author, when are you planning to release the code??

**Comment by NeoAnthropocene** [comment]
Dear @LituRout , 
The AI community follows this project closely. You may not know it, but hundreds of people like us are always looking forward to the release of this project's source code.

Would it be possible for you to share any information about the release date of our project?

**Comment by LituRout** [comment]
Hi Everyone,

Thank you so much for your interest in RB-Modulation. The code is finally cleaned up and the jupyter notebook is ready as many of you requested for it. Currently, the code is going through one review process. Most probably, it'll be released by early next week. 

Thanks for your patience. 

Best,
Litu

**Comment by poluramus** [comment]
> Hi Everyone,
> 
> Thank you so much for your interest in RB-Modulation. The code is finally cleaned up and the jupyter notebook is ready as many of you requested for it. Currently, the code is going through one review process. Most probably, it'll be released by early next week.
> 
> Thanks for your patience.
> 
> Best, Litu

Thank you very much for the updates, sir. They are greatly appreciated.

**Comment by LituRout** [comment]
Hi Everyone, 

One quick update regarding the code release. We have received most of the approvals needed. However, one final approval still remains and might get delayed due to holidays. We are trying our best to share with you as soon as we can. Thanks for your patience. 

Best,
Litu

**Comment by loboere** [comment]
any news?

**Comment by poluramus** [comment]
> any news?

Long holidays 😴

**Comment by NeoAnthropocene** [comment]
I'm checking here every beginning of the week 🤓

**Comment by junjiexv** [comment]
Any news?

**Comment by nullarch** [comment]
From a product usage perspective, those who are waiting should not wait. I think the code will not be released. Google has had many papers like Dreambooth in the past, but only some of them actually had their code released. Even if it is released, I believe it will be after other papers with superior performance have already had their code released.

**Comment by abflow** [comment]
Curious to see how the method compares with CSGO: https://csgo-gen.github.io/

**Comment by LituRout** [comment]
Hi All, we are happy to release our source code at [https://github.com/google/RB-Modulation](https://github.com/google/RB-Modulation). Look forward to interesting new developments from the AI community along this line of research.
